spring.application.name=band-api

spring.datasource.url=jdbc:postgresql://localhost:5432/band_api
spring.datasource.username=band_api_user
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=uma-chave-super-secreta-com-pelo-menos-256-bits-para-o-band-api
jwt.expiration=86400000

server.port=8080